stages:
    - test

test repo:
    stage: test
    script:
        - mkdir component-watcher 
        - rsync -av --exclude='component-watcher' * component-watcher/
        - rsync -av component-watcher /usr/tmp
