---
- name: Ensure component_path exists
  file:
    path: "{{ component_path }}"
    state: directory
    mode: '0755'

- name: Ensure config_path exists
  file:
    path: "{{ component_path }}/config"
    state: directory
    mode: '0755'

- name: Ensure log_path exists
  file:
    path: "{{ component_path }}/logs"
    state: directory
    mode: '0755'
